### ISSUE TITLE
Update for ILIAS 5.4

### ISSUE THREAD

**Issue by mglaubitz** [kyro46/assJSMEQuestion#9]
Do you have any plans for updating the question type plugin to ILIAS 5.4? We are currently building questions with this marvellous plugin and need to update to 5.4 soon.
If you need funding or any other kind of support, please let us know :)

Thanks a lot in advance!

**Comment by kyro46** [comment]
Issue resolved on May, 19, 2019. Today even updated for ILIAS 6.
